language: python
sudo: false
dist: bionic

cache: pip

python:
  - "3.6"
  - "3.7"

addons:
  apt:
    packages:
      - sqlite3
      - fping
      - gdal-bin
      - libproj-dev
      - libgeos-dev
      - libspatialite-dev
      - spatialite-bin
      - libsqlite3-mod-spatialite

services:
  - docker
  - redis-server

branches:
  only:
    - master

before_install:
  - docker run -d --name influxdb -p 8086:8086 influxdb
  - docker exec -it influxdb influx -execute 'CREATE DATABASE openwisp2'
  - pip install -U pip wheel setuptools
  - pip install --no-cache-dir -U -r requirements.txt -r requirements-test.txt

install:
  - python setup.py -q develop

script:
  - |
    openwisp-utils-qa-checks \
          --migration-path ./openwisp_monitoring/monitoring \
          --migration-module monitoring
  - coverage run --source=openwisp_monitoring runtests.py

after_success:
  coveralls
